MEMORY
{
  /* ESP32-C3 SRAM 1 (Data RAM) */
  RAM (xrw) : ORIGIN = 0x3FC80000, LENGTH = 328K
  /* ESP32-C3 ROM / Flash mapped */
  FLASH (rx) : ORIGIN = 0x42000000, LENGTH = 4M
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
